export const SET_RADIUS = "SET_RADIUS";
export const REMOVE_RADIUS = "REMOVE_RADIUS";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

export const SESSION_RESTORING = "SESSION_RESTORING";
export const SESSION_LOADING = "SESSION_LOADING";
export const SESSION_SUCCESS = "SESSION_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SESSION_ERROR = "SESSION_ERROR";
export const SESSION_LOGOUT = "SESSION_LOGOUT";
