export const SET_RADIUS = "SET_RADIUS";
export const REMOVE_RADIUS = "REMOVE_RADIUS";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

export const AUTHENTICATE = "AUTHENTICATE";
export const LOGOUT = "LOGOUT";
